import pandas as pd

game_data = pd.read_csv("datasets/Video_Games_Sales_as_at_22_Dec_2016.csv")
game_data.drop(
    [
        "Critic_Score",
        "User_Score",
        "NA_Sales",
        "EU_Sales",
        "JP_Sales",
        "Other_Sales",
    ],
    axis=1,
    inplace=True,
)
game_data = game_data.dropna()
game_data.reset_index(inplace=True)
game_data = game_data.drop("index", axis=1)
print("Sales Range:", game_data["Global_Sales"].min(), game_data["Global_Sales"].max())
game_data["Year_of_Release"].apply(lambda x: (int(str(x)[0:4])))
platform_groups = {
    "Nintendo DS": ["DS", "3DS"],
    "PlayStation": ["PS2", "PS3", "PS4", "PSV", "PSP"],
    "Xbox": ["XB", "X360", "XOne"],
    "Nintendo": ["N64", "GC", "NES", "SNES", "Wii", "WiiU", "NS"],
    "Sega": ["GEN", "SCD"],
    "Atari": ["2600"],
    "PC": ["PC", "OSX"],
    "Other Handhelds": ["GBA", "WS", "NG", "GG"],
    "Other Consoles": [
        "DC",
        "PSN",
        "XBL",
        "GBC",
        "VC",
        "3DO",
        "PCE",
        "PCFX",
        "WW",
        "Mob",
    ],
}
game_data["Platform"] = game_data["Platform"].apply(
    lambda x: next((k for k, v in platform_groups.items() if x in v), "Other_plat")
)
data = game_data[
    ["Platform", "Genre", "Publisher", "Global_Sales", "Developer", "Rating"]
]

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
data = data.assign(Publisher=data["Publisher"])
data[
    [
        "Rating_Encoded",
        "Developer_Encoded",
        "Publisher_Encoded",
        "Genre_Encoded",
        "Platform_Encoded",
    ]
] = encoder.fit_transform(
    data[["Rating", "Developer", "Publisher", "Genre", "Platform"]]
)

from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X_train, X_test, Y_train, Y_test = train_test_split(
    data[
        [
            "Rating_Encoded",
            "Developer_Encoded",
            "Publisher_Encoded",
            "Genre_Encoded",
            "Platform_Encoded",
        ]
    ],
    data[["Global_Sales"]],
    test_size=0.25,
    random_state=8693,
)
xgb_r = XGBRegressor(objective="reg:squarederror", n_estimators=15)
xgb_r.fit(X_train, Y_train)
Y_pred = xgb_r.predict(X_test)
print("Mean Absolute Error:", mean_absolute_error(Y_test, Y_pred))


# # Wrapper Code
class ModelWrapper:
    def __init__(self, model, encoder):
        self.model = model
        self.encoder = encoder

    def predict(self, arg_dict):
        import pandas as pd

        arg_df = pd.DataFrame([arg_dict])
        arg = pd.DataFrame(
            self.encoder.transform(
                arg_df[["Rating", "Developer", "Publisher", "Genre", "Platform"]]
            ),
            columns=[
                "Rating_Encoded",
                "Developer_Encoded",
                "Publisher_Encoded",
                "Genre_Encoded",
                "Platform_Encoded",
            ],
        )

        return self.model.predict(arg)


sample_dict = {
    "Rating": "E",
    "Developer": "Nintendo",
    "Publisher": "Nintendo",
    "Genre": "Sports",
    "Platform": "Nintendo DS",
}
wrapper = ModelWrapper(xgb_r, encoder)
print(wrapper.predict(sample_dict))

# Wrapper Code
import db

model_adder = db.Model()
model_adder.add_model(
    name="steam_sales_prediction",
    description="""
    The model is designed to help predict how well games will sell on the Steam platform using XGBoost. It does this by analyzing information from different games, like their genre, price, developer, publisher, and ratings. By looking at patterns in the data, the model can make predictions about how popular a game might be.
    """,
    model=wrapper,
    input_fields=[
        {
            "identifier": "Rating",
            "label": "Select Rating: ",
            "type": "select",
            "options": ["E", "M", "T", "E10+", "AO", "K-A", "RP"],
        },
        {
            "identifier": "Developer",
            "label": "Select Developer:",
            "type": "select",
            "options": [
                "Nintendo",
                "Good Science Studio",
                "Rockstar North",
                "Polyphony Digital",
                "Infinity Ward, Sledgehammer Games",
                "Treyarch",
                "Infinity Ward",
                "DMA Design",
                "Game Arts",
                "Retro Studios, Entertainment Analysis & Development Division",
                "Bungie Software, Bungie",
                "Ubisoft",
                "Bungie",
                "SquareSoft",
                "343 Industries",
                "Hudson Soft",
                "Bethesda Game Studios",
                "EA Sports",
                "Bungie Software",
                "Nd Cube",
                "Hudson",
                "Electronic Arts",
                "The Sims Studio",
                "Game Freak",
                "Rockstar Leeds",
                "Sledgehammer Games",
                "EA Sports, EA Vancouver",
                "Nintendo EAD Tokyo",
                "EA DICE",
                "EA Black Box",
                "Ubisoft Paris",
                "Namco",
                "Naughty Dog",
                "HAL Labs",
                "EA Canada",
                "EA LA",
                "Epic Games",
                "Rockstar San Diego",
                "Retro Studios",
                "Blizzard Entertainment",
                "Reflections Interactive",
                "Rare Ltd.",
                "KCEJ",
                "Kojima Productions",
                "Square Enix",
                "SCE/WWS, Media Molecule",
                "Capcom",
                "Level 5",
                "Traveller's Tales",
                "Taito Corporation",
                "Ubisoft Montreal",
                "Turn 10",
                "Rocksteady Studios",
                "Intelligent Systems",
                "Harmonix Music Systems",
                "Lionhead Studios",
                "Neversoft Entertainment",
                "Neversoft Entertainment, BudCat",
                "Naughty Dog, SCE/WWS",
                "SCE Santa Monica",
                "TT Fusion",
                "Stormfront Studios",
                "Core Design Ltd.",
                "Bluepoint Games",
                "Vicarious Visions",
                "Next Level Games",
                "EA Tiburon",
                "Konami",
                "Bethesda Softworks",
                "Ubisoft Paris, Ubisoft Montpellier",
                "Insomniac Games",
                "Mass Media",
                "Ready at Dawn",
                "SCEE, Zoe Mode",
                "Valve Software",
                "Obsidian Entertainment",
                "Cat Daddy Games",
                "CD Projekt Red Studio",
                "Ubisoft, Ubisoft Montreal",
                "Visual Concepts",
                "Evolution Studios",
                "KCET",
                "SCEA, Zindagi Games",
                "Nintendo, Namco Bandai Games",
                "Massive Entertainment",
                "Maxis",
                "Argonaut Games",
                "TOSE",
                "Zipper Interactive",
                "Pandemic Studios",
                "Fox Interactive",
                "Office Create",
                "Team Soho",
                "EA Redwood Shores",
                "Certain Affinity",
                "Agenda",
                "Gearbox Software",
                "Kojima Productions, Moby Dick Studio",
                "Media Molecule",
                "Eurocom Entertainment Software",
                "Ubisoft Quebec",
                "Double Helix Games",
                "Rockstar Toronto",
                "EA Games",
                "Splash Damage, The Coalition",
                "Luxoflux, Inc.",
                "Shiny Entertainment",
                "Team Bondi",
                "Dimps Corporation, Sonic Team",
                "Indies Zero",
                "4J Studios",
                "BioWare",
                "Dimps Corporation",
                "Quantic Dream",
                "Volition Inc.",
                "Guerrilla",
                "Junction Point",
                "Spike, Namco Bandai Games",
                "LucasArts, BioWare",
                "Monolith Productions",
                "Sonic Team",
                "Io Interactive",
                "Respawn Entertainment",
                "Sucker Punch",
                "Sumo Digital",
                "Clap Hanz",
                "OfficeCreate",
                "Spark Unlimited",
                "NetherRealm Studios",
                "Irrational Games, 2K Marin",
                "EA DICE, Danger Close",
                "NuFX",
                "Criterion Games",
                "Toys for Bob",
                "Warner Bros. Interactive Entertainment, NetherRealm Studios",
                "Edge of Reality",
                "LucasArts",
                "Artoon",
                "Namco Bandai Games",
                "Dreamworks Interactive",
                "Big Blue Box",
                "Ubisoft Shanghai",
                "Slightly Mad Studios",
                "Team Fusion",
                "Angel Studios",
                "Ensemble Studios",
                "Dice, Danger Close",
                "syn Sophia",
                "Yuke's",
                "Genius Sonority Inc.",
                "Acclaim Studios Cheltenham",
                "Headstrong Games",
                "CAProduction",
                "Raven Software",
                "Midway",
                "From Software",
                "Black Rock Studio",
                "Rainbow Studios",
                "Black Box",
                "Techland",
                "Heavy Iron Studios",
                "Pipeworks Software, Inc.",
                "Frontier Developments",
                "GREZZO",
                "Rare Ltd., BigPark",
                "ArenaNet",
                "WB Games Montreal",
                "HAL Labs, Creatures Inc.",
                "Backbone Entertainment",
                "Sega",
                "Digital Eclipse",
                "TT Games",
                "2K Marin",
                "5TH Cell",
                "Amaze Entertainment",
                "Bizarre Creations",
                "Omega Force",
                "Visceral Games",
                "Blue Planet Software",
                "Matrix Software",
                "Full Fat",
                "EA Vancouver",
                "Ubisoft Montpellier",
                "ChunSoft",
                "Midway Studios - San Diego",
                "Acquire",
                "h.a.n.d. Inc.",
                "Ghost Games",
                "Check Six Games",
                "PLAYGROUND, Playground Games",
                "Aki Corp.",
                "Flagship, HAL Labs",
                "Exakt",
                "Irrational Games",
                "Nintendo, Nd Cube",
                "NanaOn-Sha",
                "Factor 5",
                "Papaya Studios",
                "SCEI",
                "Krome Studios",
                "Avalanche Studios",
                "Jupiter Corporation",
                "Rockstar Studios",
                "Altron",
                "Creative Assembly",
                "Sega AM2",
                "Hangar 13",
                "Tango Gameworks",
                "SCEE London Studio",
                "Genuine Games",
                "Team Ninja",
                "THQ",
                "Camelot Software Planning",
                "Red Storm Entertainment",
                "VIS Entertainment",
                "Realtime Worlds",
                "Monolith Soft",
                "Terminal Reality",
                "Ready at Dawn, SCE Santa Monica",
                "SCE Japan Studio",
                "ArtePiazza",
                "Ubisoft Reflections, Ivory Tower",
                "Tri-Ace",
                "Arkane Studios",
                "Artefacts Studio",
                "Hello Games",
                "Griptonite Games",
                "Webfoot Technologies",
                "Firaxis Games",
                "Bandai Namco Games",
                "Rebellion",
                "Shaba Games",
                "Paradigm Entertainment",
                "EA Chicago",
                "SuperMassive Games",
                "HB Studios Multimedia",
                "EA Sports Big",
                "Spike",
                "Ninja Theory",
                "EA Montreal",
                "id Software",
                "Capcom Vancouver",
                "Pivotal Games",
                "MachineGames",
                "2K Czech",
                "Naughty Dog, Sony Bend",
                "Cavia Inc.",
                "The Code Monkeys",
                "Amusement Vision",
                "Sports Interactive",
                "Genki",
                "Blue Castle Games",
                "Kush Games",
                "Nihilistic",
                "Kaos Studios",
                "Hellbent Games",
                "Avalanche Software",
                "Blitz Games",
                "BigPark",
                "Planet Moon Studios",
                "Blue Byte, Related Designs",
                "EA Bright Light",
                "Digital Extremes, 2K Marin",
                "Sand Grain Studios",
                "Flagship",
                "PlatinumGames",
                "Danger Close",
                "Incognito Inc.",
                "Codemasters",
                "Playground Games",
                "Arzest",
                "Crytek",
                "Crystal Dynamics",
                "Sega, Sonic Team",
                "Z-Axis, Ltd.",
                "Now Production",
                "Eidos Montreal",
                "Square Enix, Think and Feel",
                "The Coalition",
                "Pitbull Syndicate",
                "Codemasters Birmingham",
                "Rockstar Vienna",
                "Remedy Entertainment",
                "Steel Monkeys",
                "Acclaim",
                "Radical Entertainment",
                "Good-Feel",
                "SCEA",
                "Namco Bandai Games America, Namco Bandai Games",
                "Creatures Inc.",
                "Pocket Studios",
                "M2",
                "Melbourne House",
                "Ubisoft Sofia",
                "ZeniMax Media",
                "Snowblind Studios",
                "Opus, Project Sora",
                "Nintendo, Spike Chunsoft",
                "CyberConnect2",
                "3G Studios",
                "Tamsoft",
                "THQ, Yuke's",
                "Virtuos",
                "Nixxes Software",
                "Slant Six",
                "Tarsier Studios, Double Eleven",
                "Spike Chunsoft Co. Ltd., Spike Chunsoft",
                "Chris Sawyer",
                "49Games",
                "Oddworld Inhabitants",
                "High Voltage Software",
                "neo Software",
                "Savage Entertainment",
                "Nex Entertainment",
                "Surreal Software",
                "Climax Group",
                "Locomotive Games",
                "Nintendo, Nintendo Software Technology",
                "Omega Force, Tecmo Koei Games",
                "Light Weight",
                "City Interactive",
                "K2 LLC",
                "Ambrella",
                "Konami Computer Entertainment Hawaii",
                "Day 1 Studios",
                "Helixe",
                "Level 5, Brownie Brown",
                "United Front Games",
                "BudCat",
                "Ryu ga Gotoku Studios",
                "Atlus",
                "Ruffian Games",
                "Mercury Steam",
                "EA Redwood Shores, EA Salt Lake",
                "Sony Online Entertainment",
                "Ubisoft Shanghai/Paris",
                "PopCap",
                "Electronic Arts, Rebellion",
                "SCEE",
                "Page 44 Studios",
                "FreeStyleGames",
                "Mad Doc Software, Rockstar Vancouver",
                "Blizzard North",
                "Arika",
                "Barnhouse Effect",
                "Vigil Games",
                "n-Space",
                "Microsoft Game Studios",
                "Sega AM3",
                "8ing/Raizing",
                "Electronic Arts, EA Redwood Shores",
                "Splash Damage",
                "Studio Liverpool",
                "Red Storm Entertainment, Ubisoft Paris",
                "Tantalus Interactive, Tantatus, Nintendo",
                "Crystal Dynamics, Nixxes Software",
                "Bigbig Studios",
                "EA Salt Lake",
                "Longtail Studios",
                "Epic Games, People Can Fly",
                "Sega, Dimps Corporation",
                "Koei",
                "Project Aces",
                "Team Ninja, Tecmo",
                "Razorworks Studios",
                "UBlart Montpellier",
                "Free Radical Design",
                "DreamFactory",
                "Rockstar London",
                "Ubisoft Toronto",
                "Double Fine Productions",
                "Turtle Rock Studios",
                "Giants Software",
                "Vicarious Visions, Neversoft Entertainment",
                "Blue Tongue Entertainment",
                "Overworks",
                "Monster Games Inc.",
                "Coresoft",
                "SuperBot Entertainment",
                "Ubisoft Reflections",
                "Alfa System",
                "Buzz Monkey",
                "Rockstar Vancouver",
                "SCEA San Diego Studios",
                "Neko Entertainment",
                "Square Enix, h.a.n.d. Inc.",
                "Activision",
                "KCE Studios",
                "Titus Software",
                "Black Ops Entertainment",
                "Tantalus Interactive",
                "Mistwalker, Artoon",
                "Marvelous AQL",
                "Xpec",
                "Mistwalker",
                "989 Sports",
                "Magic Pockets",
                "KCEK",
                "Sony Bend",
                "RED Entertainment",
                "FASA Studio",
                "Runecraft",
                "Big Huge Games",
                "Media Molecule, United Front Games",
                "SCi",
                "Cooking Mama Limited",
                "Red Fly Studio",
                "Rage Software",
                "Toolbox Design",
                "Team 17",
                "Dimps Corporation, Namco Bandai Games",
                "Asobo Studio",
                "Eutechnyx",
                "Visual Impact",
                "Gearbox Software, 3D Realms",
                "Artificial Mind and Movement",
                "Digital Anvil",
                "Treyarch, Sledgehammer Games",
                "Marvelous Entertainment",
                "EA Seattle",
                "Indie Built",
                "Atlus Co.",
                "Capcom, Pipeworks Software, Inc.",
                "Monkey Bar Games",
                "Guerilla Cambridge",
                "Marvelous",
                "Deibus Studios",
                "Square Enix, Tri-Ace",
                "Novarama",
                "Silicon Knights",
                "Kush Games, Visual Concepts",
                "iNiS",
                "EA Canada, Nihilistic",
                "Eden Studios",
                "David A. Palmer Productions",
                "Artificial Mind and Movement, Polygon Magic",
                "Acclaim Studios Austin",
                "Piranha Games",
                "Exient Entertainment",
                "LucasArts, Red Fly Studio",
                "Game Republic",
                "Project Soul",
                "Propaganda Games",
                "JGI Entertainment",
                "Digital Extremes",
                "Brownie Brown",
                "Natsume",
                "Arc System Works",
                "CyberConnect2, Racjin",
                "Dearsoft",
                "Paradox Development",
                "2K Australia",
                "Realism Ltd",
                "Bandai",
                "Equinoxe",
                "Pacific Coast Power & Light",
                "Koei, Omega Force",
                "id Software, Nerve Software",
                "Eighting, Genius Sonority Inc.",
                "Reality Pump",
                "Illusion Softworks",
                "SCEA, Sims",
                "Kalypso",
                "Midway Studios - Los Angeles",
                "Ubisoft Milan",
                "Fuse Games Limited",
                "Pyramid",
                "Hypnos Entertainment",
                "Black Isle Studios",
                "Gaijin Entertainment",
                "Sanzaru Games",
                "Tomy Corporation",
                "Secret Level",
                "Nerve Software",
                "Trion Worlds",
                "BioWare, Demiurge Studios",
                "Engine Software",
                "RED Entertainment, Artdink",
                "Starbreeze",
                "Delphine Software International",
                "Grasshopper Manufacture",
                "Shift, Bandai Namco Games",
                "Dimps Corporation, SCE Japan Studio",
                "Krome Studios, Screenlife Games",
                "Suzak",
                "Iron Galaxy Studios",
                "GenePool",
                "Ubisoft Casablanca",
                "Epicenter Studios",
                "Adrenium",
                "Juice Games",
                "id Software, Raven Software",
                "SEGA Racing Studio",
                "Clover Studio",
                "EA Sports, EA Canada",
                "Media Vision, Contrail",
                "Paon Corporation",
                "Lab Rats Games",
                "Vicious Cycle",
                "High Impact Games",
                "Skyworks Technologies",
                "Robomodo",
                "Ascaron Entertainment GmbH, Ascaron Entertainment",
                "2K Sports",
                "Appaloosa Interactive",
                "Vanillaware",
                "Dreamworks Games",
                "Gameloft",
                "Atomic Planet Entertainment",
                "Coldwood Interactive",
                "Valuewave Co.,Ltd.",
                "Pam Development",
                "Farsight Studios",
                "Beenox",
                "Ubisoft Romania",
                "Spicy Horse",
                "Overkill Software",
                "Midway Studios - Austin",
                "Bunkasha Publishing",
                "Nippon Ichi Software",
                "Digital Illusions",
                "Neverland",
                "Silicon Studio",
                "Vanilla Ware",
                "Etranges Libellules",
                "Relic",
                "Anchor",
                "Racjin",
                "Magenta Software",
                "Tetris Online, Inc",
                "Awesome Studios",
                "Pipe Dream Interactive",
                "Bullets",
                "Aspect",
                "Deep Space",
                "Inti",
                "THQ Digital Studio Phoenix",
                "Brain Toys",
                "Hothouse Creations",
                "Nuevo Retro Games",
                "Yager",
                "Omega Force, Koei Tecmo Games",
                "4A Games",
                "Cing",
                "WXP",
                "Inevitable Entertainment",
                "Destineer",
                "Eighting",
                "SCEA Sports Studio",
                "High Voltage Software, Ubisoft Paris",
                "Incinerator Games",
                "GRIN",
                "Q-Games",
                "Raster",
                "Vivarium",
                "MTO",
                "Machatin, Inc.",
                "City Interactive, Deck 13",
                "Climax Group, Climax Studios",
                "HexaDrive",
                "Blitz Games Studios",
                "Jupiter Corporation, Jupiter Multimedia",
                "Blade Interactive",
                "Factor 5, SCE/WWS",
                "SCE Japan Studio, comcept",
                "WBIE",
                "Warthog",
                "AWE Games",
                "Contraband Entertainment",
                "Eugen Systems",
                "Quest",
                "Kuusou Kagaku",
                "7 Studios",
                "WayForward",
                "Pocketeers",
                "Harmonix Music Systems, Backbone Entertainment",
                "Zoe Mode",
                "Screenlife Games, WXP",
                "Totally Games",
                "Bullfrog Productions",
                "Ratbag",
                "SCEJ",
                "Razorworks",
                "New",
                "Beyond Games",
                "Ubisoft Barcelona, Ubisoft Reflections",
                "Eurocom Entertainment Software, Visceral Games",
                "Nintendo, Headstrong Games",
                "ImaginEngine",
                "Tecmo",
                "Vatra",
                "Treasure",
                "Eighting/Raizing",
                "Studio Gigante",
                "High Moon Studios",
                "Wideload Games Inc.",
                "Computer Artworks",
                "Saffire",
                "Nintendo, Camelot Software Planning",
                "Team 17, Two Tribes",
                "Point of View",
                "Square Enix, TOSE",
                "Q Entertainment",
                "Tri-Crescendo",
                "LucasArts, Krome Studios",
                "Idea Factory, Compile Heart",
                "Kamui",
                "War Drum Studios",
                "TOYBOX",
                "Sunrise Interactive",
                "Gust",
                "Ritual Entertainment, Avalanche Software",
                "Psygnosis",
                "Armature Studio",
                "Atari",
                "RedLynx",
                "Creat Studios",
                "Nintendo, Intelligent Systems",
                "Spike Chunsoft",
                "Red Storm Entertainment, Ubisoft Montreal",
                "Saber Interactive",
                "Maximum Games",
                "Collision Studios",
                "Harmonix Music Systems, Demiurge Studios",
                "Triumph Studios",
                "DONTNOD Entertainment",
                "Kuju Entertainment",
                "Twisted Pixel Games",
                "Zen Studios",
                "Jester Interactive",
                "Frogwares, Mistic Software",
                "Prope",
                "Wow Entertainment",
                "Monolith Soft, Banpresto",
                "Sega Studios San Francisco",
                "Ganbarion",
                "Milestone S.r.l",
                "Red Tribe",
                "Red Zone Entertainment",
                "Amuze",
                "Bugbear",
                "Cyberlore Studios",
                "Lightning Fish Games",
                "Firebrand Games",
                "Crafts & Meister",
                "3DO",
                "Blueside",
                "Noise Inc.",
                "2K Games",
                "Psyonix",
                "Takara Tomy",
                "KCEO",
                "Zombie Studios",
                "Bandai Namco Games, Artdink",
                "Pax Softonica",
                "Zener Works",
                "UDS",
                "RED Entertainment, Spike Chunsoft",
                "Cattle Call",
                "Inland Productions",
                "ITL",
                "Sandlot",
                "Airtight Games",
                "Take-Two Interactive",
                "Deep Silver Dambuster Studios",
                "Destination Software",
                "High Voltage Software, Backbone Entertainment",
                "Nadeo",
                "Sennari Interactive",
                "Gas Powered Games",
                "Tantatus",
                "Buena Vista Interactive",
                "Cohort Studios",
                "1st Playable Productions",
                "EA Canada, EA Vancouver",
                "Inti Creates",
                "Shift",
                "Ion Storm",
                "SNK Playmore",
                "Smart Bomb Interactive",
                "SunSoft",
                "Lancarse, Atlus",
                "AI",
                "Eidos Interactive",
                "Terminal Reality, 4mm Games",
                "Victor Interactive Software",
                "Polygon Magic",
                "Hijinx Studios",
                "Buzz Monkey, EA Montreal",
                "Atlus, Dingo Inc.",
                "Opus",
                "Venom Games",
                "Game Republic, JapanStudio",
                "Phantagram",
                "Mercury Steam, Alchemic Productions",
                "Access Games",
                "Image Epoch, Imageepoch",
                "Human Head Studios",
                "Big Red Button Entertainment",
                "Blue Byte",
                "Haemimont",
                "Wildfire Studios",
                "Sidhe Interactive",
                "Inti, Inti Creates",
                "Mucky Foot Productions",
                "Ronin Entertainment",
                "Disney Interactive",
                "Artdink",
                "Shade",
                "Prolific",
                "Idol Minds",
                "SCE Studio Cambridge",
                "Banpresto, SoftMax",
                "Graphic State",
                "Related Designs",
                "The Workshop",
                "Neversoft Entertainment, Underground Development",
                "Simon & Schuster",
                "Mistic Software",
                "IR Gurus",
                "LightBox Interactive",
                "Akella",
                "Wargaming.net",
                "Game Titan",
                "Sacnoth",
                "Cave",
                "Just Add Monsters",
                "Volatile Games",
                "Media Vision",
                "Ignition Entertainment",
                "Zindagi Games",
                "Zoom",
                "Presto Studios",
                "Zoe Mode, HB Studios Multimedia",
                "Arcade Moon",
                "Rockstar Toronto, Rockstar Leeds",
                "Ubisoft Vancouver",
                "Ubisoft, Sensory Sweep",
                "TimeGate Studios",
                "Pacific Century Cyber Works",
                "LDW, Big Fish Games",
                "Rocksteady Studios, Virtuos",
                "Smilebit",
                "Blue Shift",
                "Rovio Mobile, Rovio Entertainment",
                "Metro",
                "Hypnotix",
                "Treyarch, Shaba Games",
                "Prokion",
                "Crispy's",
                "DC Studios",
                "Left Field Productions",
                "Gorilla Systems",
                "Mitchell",
                "Cyanide, Cyanide Studios",
                "FuRyu",
                "Sony Interactive Entertainment",
                "InXile Entertainment",
                "2015",
                "ZootFly",
                "Southend Interactive",
                "Amaze",
                "Bec",
                "Io Interactive, Nixxes Software",
                "Tamsoft, D3Publisher",
                "Falcom",
                "Metro Graphics",
                "Matrix Software, Marvelous Entertainment",
                "Nautilus",
                "Frogwares",
                "Oxygen Interactive",
                "Revolution Software",
                "Larian Studios",
                "Blueshift",
                "VU Games",
                "Compile Heart",
                "Magic Pixel Games",
                "Disney Interactive Studios",
                "Gratuitous Games",
                "Blue Tongue",
                "K2",
                "Bits Studios",
                "Piranha Bytes",
                "Alphadream Corporation",
                "Tecmo Koei Games",
                "Tecmo, Ntreev Soft",
                "Monumental Games",
                "Climax Entertainment",
                "Secret Stash Games",
                "Data Design Interactive",
                "GungHo",
                "SoftMax",
                "Career Soft",
                "AQ Interactive",
                "Art",
                "Pseudo Interactive",
                "Rhino Studios",
                "Irem",
                "Lucky Chicken",
                "MASA Group",
                "Swordfish Studios",
                "ThatGameCompany",
                "Osiris Studios",
                "FUN Labs",
                "Telltale Games",
                "Deep Silver, Sproing Interactive Media, Sproing",
                "2XL Games",
                "Jellyvision, Iron Galaxy Studios",
                "Bongfish",
                "Cranky Pants Games",
                "Sun-Tec",
                "Alpha Unit",
                "Takara",
                "Sanzaru Games, Sanzaru Games, Inc.",
                "CCP",
                "Hitmaker",
                "Behaviour Interactive",
                "SCEA, Think and Feel",
                "Studio Saizensen",
                "Ubisoft Annecy",
                "Pyro Studios",
                "WideScreen Games",
                "Gaming Minds Studios",
                "Omega Force, Koei Canada",
                "Torus Games",
                "Big Sky Software",
                "Cauldron Ltd.",
                "Sega, Tom Create",
                "Mad Catz",
                "Examu",
                "FeelPlus",
                "Spiders",
                "GCP1",
                "Phoenix Games Studio",
                "Zono Inc.",
                "Keen Games",
                "Activision, FreeStyleGames",
                "Software Creations",
                "Magic Rings",
                "Artificial Mind and Movement, EA Redwood Shores",
                "Santa Cruz Games",
                "Seta Corporation",
                "BottleRocket Entertainment",
                "Skip Ltd.",
                "Cinemaware",
                "Tecmo Koei Canada",
                "Spellbound",
                "Buena Vista Games",
                "D3Publisher",
                "Teyon",
                "Kronos Digital Entertainment",
                "Coyote Developments",
                "Majesco Games, Majesco",
                "5pb",
                "Hydravision",
                "Brash Entertainment",
                "Marvelous Inc.",
                "Big Ant Studios",
                "Backbone Emeryville",
                "Gust, Idea Factory",
                "Lost Toys",
                "Eighting, Takara Tomy",
                "Koei Tecmo Games",
                "Replay Studios, ML Enterprises",
                "Namco Bandai Games, Cellius",
                "SimBin",
                "Swingin' Ape",
                "Funcom",
                "Jaleco Entertainment",
                "Deep Silver",
                "Playlogic, The Game Factory",
                "T&E Soft",
                "Experience Inc.",
                "Human Entertainment",
                "Kylotonn",
                "Stalker Entertainment",
                "Renegade Kid",
                "Artech Studios",
                "Cyanide",
                "Buddiez, Inc.",
                "Lucas Learning",
                "Sega, French-Bread",
                "WinkySoft",
                "Gearbox Software, WayForward",
                "SScholastic Media",
                "Hudson Entertainment",
                "SuperVillain Studios",
                "Omiya Soft, Jamsworks",
                "Atari, Transmission Games, Atari SA",
                "System 3",
                "Sony Online Entertainment, Mind Control Software",
                "Carbine Studios",
                "Tenky",
                "Bam Entertainment",
                "Compile Heart, GCREST",
                "Broadsword Interactive",
                "Game Arts, Seta Corporation",
                "Magellan Interactive",
                "Aqua Plus",
                "Infinite Interactive",
                "Croteam",
                "Zombie",
                "THQ Australia",
                "Hypnos",
                "Crawfish Interactive",
                "Warner Bros. Interactive Entertainment",
                "Interchannel",
                "Netherock Ltd.",
                "Felistella",
                "Armature Studio, comcept",
                "Sensory Sweep",
                "Ubisoft Bulgaria",
                "Re-Logic",
                "Nicalis",
                "Zerodiv",
                "Liquid Entertainment",
                "Sting",
                "Mix Max",
                "Microvision",
                "Ntreev Soft",
                "Epics",
                "Westwood Studios",
                "FrontLine Studios",
                "Studio 33",
                "Bohemia Interactive",
                "Colossal Order",
                "Flight-Plan",
                "Yacht Club Games",
                "Seven45 Studios",
                "TopWare Interactive",
                "The Fun Pimps Entertainment LLC",
                "Next Entertainment",
                "Transmission Games",
                "K2, Kurogane",
                "Crave",
                "Gaijin Games",
                "Attention To Detail",
                "Tripwire Interactive",
                "JV Games Inc.",
                "Top Heavy Studios",
                "Panic Button",
                "Taniko",
                "Circus Freak",
                "Virtual Air Guitar Company",
                "Venan Entertainment, Cashmere Prod.",
                "Sunflowers Interactive",
                "Rocksteady Studios, Iron Galaxy Studios",
                "Deck 13",
                "IR Gurus Interactive Ltd.",
                "Phosphor Games Studio, LLC",
                "Outrage Games",
                "Platinum Egg",
                "Humongous Entertainment",
                "Premium Agency",
                "Syscom",
                "GlyphX Games",
                "Hot Lava Games",
                "Nfusion",
                "Curly Monsters",
                "Psikyo",
                "Deep Fried Entertainment",
                "Beep Industries",
                "I-Imagine",
                "Stormregion",
                "Kung Fu Factory",
                "Game Arts, Japan Art Media (JAM)",
                "Infogrames",
                "Acclaim Studios Manchester",
                "Prope, Kadokawa",
                "Moss",
                "RFX Interactive",
                "369 Interactive",
                "Visual Sciences",
                "Animation Arts",
                "Nippon Ichi Software, Hit Maker",
                "Artificial Studios, Immersion Software & Graphics",
                "Funatics Software, Funatics",
                "Microsoft Game Studios Japan",
                "HotGen",
                "Black Hole Games",
                "Darkworks",
                "EA Tiburon, n-Space",
                "Halfbrick Studios",
                "Trickstar Games",
                "FireFly Studios",
                "Gusto Games",
                "Santa Entertainment",
                "Digital Embryo",
                "Micro Cabin",
                "Guildford Studio",
                "Bionic Games",
                "Aqua Pacific, In2Games",
                "Happy Happening",
                "Pentavision Entertainment",
                "Immersion Software & Graphics",
                "Vanguard",
                "Full-Fat",
                "Idea Factory",
                "KING Art",
                "SNK",
                "Deep Silver, Keen Games",
                "Microids",
                "Koei/Inis",
                "Petroglyph",
                "Monolith Soft, Namco Bandai Games",
                "Digital Mayhem",
                "Daedalic Entertainment",
                "Dreamcatcher",
                "Frima Studio",
                "The Behemoth",
                "Hoplite Research",
                "505 Games",
                "Kemco",
                "Starsphere Interactive",
                "Other Ocean Interactive",
                "Ivory Tower",
                "Kadokawa",
                "Milestone",
                "Loose Cannon Studios",
                "8Monkey Labs",
                "odenis studio",
                "Realmforge Studios",
                "3d6 Games",
                "Atomic Motion",
                "The Game Factory",
                "Black Ship Games",
                "BeeWorks",
                "Stainless Games",
                "Entersphere, Inc.",
                "Deadline Games",
                "ProSoft",
                "Big Blue Bubble Inc.",
                "Isopod Labs",
                "SCE/WWS, SCE Japan Studio",
                "Spark Unlimited, comcept",
                "Ambrella, The Pokemon Company",
                "Neverland, Idea Factory",
                "Hit Maker",
                "Metro3D",
                "Blue Omega",
                "Housemarque",
                "Smack Down Productions",
                "Activision, Traveller's Tales",
                "S-Neo",
                "G1M2",
                "TimeGate Studios, Day 1 Studios",
                "Indi",
                "ECI",
                "Wizarbox",
                "Gulti",
                "EA Canada, Sensory Sweep",
                "Shin'en",
                "Digital Leisure Inc.",
                "Cosmigo",
                "Noise Factory",
                "Foundation 9 Entertainment",
                "Telenet",
                "Kheops Studio",
                "Namco Bandai Games, Monkey Bar Games",
                "UGA",
                "Vivendi Games",
                "Toka",
                "Egosoft",
                "Cunning Developments",
                "Velez & Dubail",
                "Mekensleep",
                "Milestone, Milestone S.r.l",
                "Metropolis Software",
                "Spike Chunsoft, Chime",
                "Pinegrow",
                "Ubisoft Barcelona",
                "Roxor Games",
                "Fatshark AB",
                "Runic Games",
                "ValuSoft",
                "Paradox Development Studio",
                "Direct Action Games",
                "5000ft",
                "Kodiak Interactive",
                "Awesome Play Ltd.",
                "Success",
                "Vogster",
                "G-Artists",
                "Goshow",
                "Leviathan Games",
                "Box Clever Interactive",
                "Million",
                "Human Soft",
                "Sabertooth Games",
                "Ubisoft, FunHouse",
                "Coyote Console",
                "Enterbrain",
                "Climax Studios",
                "Metanet Software Inc., SilverBirch Studios",
                "Interactive Brains",
                "Powerhead Games",
                "Zed Two Limited",
                "Doublesix",
                "Synetic",
                "Zoo Games",
                "Interplay",
                "Monte Cristo Multimedia",
                "Silver Wish Games",
                "Runtime",
                "DiP Interactive",
                "IronNos Co.,Ltd.",
                "DreamRift",
                "Brainbox Games",
                "Kunos Simulazioni",
                "Nikitova Games",
                "Nitro+",
                "Sonic Powered",
                "Nordic Games Publishing",
                "EA Japan Studio",
                "Headfirst Productions",
                "Pendulo Studios",
                "10tacle Studios, Fusionsphere Systems",
                "Arkedo Studio",
                "GSC Game World",
                "Valhalla Game Studios",
                "Quicksilver Software",
                "WorkJam",
                "Orbital Media, Inc.",
                "Blue Fang Games",
                "Rebellion, Neversoft Entertainment",
                "Andamiro U.S.A. Corp.",
                "KnowWonder",
                "Eutechnyx, Deep Silver",
                "Iron Lore Entertainment",
                "Ninja Studio",
                "Codo Games",
                "Raylight Studios",
                "CI Games",
                "Imagineer",
                "1C: Maddox Games",
                "Studio Archcraft",
                "THQ, 1C, 1C Company",
                "Neon Studios",
                "Doki Denki",
                "Buka Entertainment, Targem Games",
                "Next Level Games, Nintendo",
                "EKO Software",
                "Taito Corporation, 505 Games",
                "Dusenberry Martin Racing",
                "Liquid Dragon Studios",
                "Stainless Steel Studios",
                "Max Five",
                "VSTEP",
                "Flying Tiger Development",
                "Konami Software Shanghai",
                "Bright Future GmbH",
                "SouthPeak Games",
                "SkyRiver Studios",
                "Icon Games",
                "Killaware",
                "SystemSoft",
                "G.Rev",
                "Fusionsphere Systems",
                "Examu, Marvelous Inc.",
                "Capcom, QLOC",
                "Ubisoft Osaka",
                "Snap Dragon Games",
                "Wicked Witch Software",
                "Ascaron Entertainment GmbH",
                "Atari, Slightly Mad Studios, Atari SA",
                "Nival Interactive",
                "PopTop Software",
                "Best Way",
                "Empire Interactive",
                "Iridon Interactive AB",
                "Naps Team",
                "Mad Doc Software",
                "Blue 52",
                "Rising Star Games",
                "Nightlight Studios",
                "EnjoyUp Games",
                "Tilted Mill",
                "Reloaded Productions, Reloaded Games Inc.",
                "NoWay Studio",
                "System Prisma",
                "CiRCLE",
                "Volition Inc., CD Projekt Red Studio, CD Projekt, CD Projekt Localisation Centre",
                "Frozenbyte, Inc.",
                "InLight Entertainment",
                "2D Boy",
                "Fusionsphere Systems, Animation Arts",
                "Gaia (Sony)",
                "People Can Fly",
                "Enlight Software",
                "BattleGoat Studios",
                "Super Empire",
                "Global A",
                "Volition Inc., Reactor Zero",
                "Eidos Montreal, Nixxes Software",
                "Sonnori",
                "Tiwak",
                "Opus Studio",
                "Gameinvest, Seed Studios, Lda",
                "Introversion, Double Eleven",
                "Big Time Software",
                "Viva Media, Viva Media, LLC",
                "Confounding Factor",
                "Eagle Dynamics",
                "Black Sea Studios",
                "zSlide",
                "Big Blue Bubble Inc., Breakthrough New Media",
                "Prograph",
                "NEC Interchannel",
                "Ironclad Games",
                "Panther Software",
                "Nitro Games",
                "Number None Inc., Knockout Games",
                "Legacy Interactive",
                "Mobius Entertainment",
                "Arrowhead Game Studios",
                "Activision, Behaviour Interactive",
                "Crea-Tech",
                "Games Farm",
                "Neon Studios, Kaiko",
                "PuzzleKings",
                "Gameness Art Software",
                "Mindware Studios",
                "EA Mythic",
                "Atomic Planet Entertainment, Mud Duck Productions",
                "MileStone Inc.",
                "SEK Ost",
                "The Tangentlemen",
                "Multimedia Intelligence Transfer",
                "Cryptic Studios",
                "Edge Entertainment, Anima Project",
                "1C, 1C Company",
                "Boxed Dream",
                "Lead Pursuit",
                "NATSUME ATARI Inc.",
                "Punchline, Shirogumi",
                "Namco Bandai Games America",
                "Beluga Computer",
                "InterServ International",
                "Trendy Entertainment",
                "Black Lantern Studios",
                "Mediascape, CUBETYPE",
                "JoWooD Entertainment AG",
                "Master Creating",
                "Touchdown Entertainment",
                "Turbine Inc.",
                "Playstos Entertainment",
                "Nvizzio Creations",
                "Flagship Studios",
                "ApolloSoft",
                "Infogrames Sheffield",
                "1C:Ino-Co",
                "Tose Software",
                "Pterodon",
                "Aspyr",
                "Strangelite",
                "Deep Red",
                "Tranji",
                "Vicious Cycle, Infinite Interactive",
                "Supersonic Software",
                "Cyan Worlds",
                "GameCo",
                "Babylon Software",
                "Flying Lab Software",
                "1C, Ino-Co, 1C Company",
                "Autumn Moon",
                "Tate Interactive",
                "Elixir Studios",
                "Compulsion Games",
                "Camouflaj, LLC",
                "DMA Design, Rockstar North",
                "King of the Jungle",
                "Spidersoft, Spiders",
                "Tecmo, Graphic Research",
                "Battlefront.com, 1C, 1C Company",
                "EA Phenomic",
                "Empty Clip Studios",
                "TDK Mediactive",
                "Headgate",
                "Coffee Stain Studios",
                "Activision Value",
                "Boston Animation",
                "React Games",
                "Inferno Games",
                "Katauri Interactive",
                "High Moon Studios, Mercenary Technologies",
                "Infinite Dreams, Paragon 5",
                "Big Red Software",
                "Fluid Studios",
                "Atomic Games",
            ],
        },
        {
            "identifier": "Publisher",
            "label": "Select Publisher:",
            "type": "select",
            "options": [
                "Nintendo",
                "Microsoft Game Studios",
                "Take-Two Interactive",
                "Sony Computer Entertainment",
                "Activision",
                "Ubisoft",
                "Bethesda Softworks",
                "Electronic Arts",
                "SquareSoft",
                "GT Interactive",
                "Konami Digital Entertainment",
                "Square Enix",
                "Sony Computer Entertainment Europe",
                "Virgin Interactive",
                "LucasArts",
                "505 Games",
                "Capcom",
                "Warner Bros. Interactive Entertainment",
                "Universal Interactive",
                "RedOctane",
                "Atari",
                "Eidos Interactive",
                "Namco Bandai Games",
                "Vivendi Games",
                "MTV Games",
                "Sega",
                "THQ",
                "Disney Interactive Studios",
                "Acclaim Entertainment",
                "Midway Games",
                "Deep Silver",
                "NCSoft",
                "Tecmo Koei",
                "Valve Software",
                "Infogrames",
                "Mindscape",
                "Valve",
                "Hello Games",
                "Global Star",
                "Gotham Games",
                "Crave Entertainment",
                "Hasbro Interactive",
                "Codemasters",
                "TDK Mediactive",
                "Zoo Games",
                "Sony Online Entertainment",
                "RTL",
                "D3Publisher",
                "Black Label Games",
                "SouthPeak Games",
                "Zoo Digital Publishing",
                "City Interactive",
                "Empire Interactive",
                "Russel",
                "Atlus",
                "Mastertronic",
                "Slightly Mad Studios",
                "Play It",
                "Tomy Corporation",
                "Focus Home Interactive",
                "Unknown",
                "Game Factory",
                "Titus",
                "Marvelous Entertainment",
                "Genki",
                "TalonSoft",
                "Square Enix ",
                "SCi",
                "Rage Software",
                "Ubisoft Annecy",
                "Rising Star Games",
                "Enix Corporation",
                "Level 5",
                "Koch Media",
                "Square EA",
                "Touchstone",
                "Spike",
                "Nippon Ichi Software",
                "Sony Computer Entertainment America",
                "Illusion Softworks",
                "Interplay",
                "Metro 3D",
                "Rondomedia",
                "Ghostlight",
                "Majesco Entertainment",
                "PQube",
                "Trion Worlds",
                "Xseed Games",
                "Ignition Entertainment",
                "Kadokawa Shoten",
                "Natsume",
                "Square",
                "Gamebridge",
                "Midas Interactive Entertainment",
                "ASCII Entertainment",
                "Rebellion",
                "Harmonix Music Systems",
                "Activision Blizzard",
                "Xplosiv",
                "System 3 Arcade Software",
                "Wanadoo",
                "NovaLogic",
                "BAM! Entertainment",
                "Tetris Online",
                "Psygnosis",
                "Screenlife",
                "GungHo",
                "Jester Interactive",
                "Black Bean Games",
                "3DO",
                "Takara Tomy",
                "Sammy Corporation",
                "Hudson Soft",
                "Marvelous Interactive",
                "Kalypso Media",
                "Home Entertainment Suppliers",
                "Arc System Works",
                "Banpresto",
                "Wargaming.net",
                "Destineer",
                "Pacific Century Cyber Works",
                "PopCap Games",
                "Indie Games",
                "FuRyu",
                "Nihon Falcom Corporation",
                "Gathering of Developers",
                "Oxygen Interactive",
                "DTP Entertainment",
                "Falcom Corporation",
                "Kemco",
                "Milestone S.r.l.",
                "AQ Interactive",
                "Agetec",
                "XS Games",
                "Activision Value",
                "Telltale Games",
                "Zushi Games",
                "CCP",
                "Agatsuma Entertainment",
                "Compile Heart",
                "Mad Catz",
                "Gust",
                "Media Rings",
                "JoWood Productions",
                "Brash Entertainment",
                "Funcom",
                "Jaleco",
                "Playlogic Game Factory",
                "Human Entertainment",
                "Fox Interactive",
                "Scholastic Inc.",
                "System 3",
                "Nordic Games",
                "White Park Bay Software",
                "EA Games",
                "Acquire",
                "Paradox Interactive",
                "Yacht Club Games",
                "Swing! Entertainment",
                "Hip Interactive",
                "Tripwire Interactive",
                "Enterbrain",
                "Havas Interactive",
                "Sting",
                "Idea Factory",
                "Funsta",
                "Tru Blu Entertainment",
                "Moss",
                "From Software",
                "NDA Productions",
                "Bigben Interactive",
                "Idea Factory International",
                "O-Games",
                "Funbox Media",
                "Valcon Games",
                "PM Studios",
                "Bohemia Interactive",
                "Aqua Plus",
                "Ackkstudios",
                "HMH Interactive",
                "inXile Entertainment",
                "Cave",
                "Microids",
                "Phantom EFX",
                "Evolved Games",
                "O3 Entertainment",
                "Aspyr",
                "Nobilis",
                "Sunsoft",
                "DSI Games",
                "Little Orbit",
                "Telegames",
                "The Adventure Company",
                "Popcorn Arcade",
                "Insomniac Games",
                "Aksys Games",
                "Taito",
                "Reef Entertainment",
                "Irem Software Engineering",
                "Myelin Media",
                "Success",
                "SNK",
                "Avalon Interactive",
                "Revolution Software",
                "Gamecock",
                "Groove Games",
                "Hudson Entertainment",
                "Mercury Games",
                "Ascaron Entertainment GmbH",
                "Mastiff",
                "Destination Software, Inc",
                "Graffiti",
                "1C Company",
                "Phantagram",
                "DreamCatcher Interactive",
                "Dusenberry Martin Racing",
                "Navarre Corp",
                "ESP",
                "Team17 Software",
                "Max Five",
                "Conspiracy Entertainment",
                "Milestone S.r.l",
                "Rebellion Developments",
                "Kool Kizz",
                "Monte Christo Multimedia",
                "5pb",
                "Cloud Imperium Games Corporation",
                "Flashpoint Games",
                "Alternative Software",
                "DHM Interactive",
                "Iceberg Interactive",
                "MC2 Entertainment",
                "2D Boy",
                "Gearbox Software",
                "Global A Entertainment",
                "Just Flight",
                "bitComposer Games",
                "Introversion Software",
                "Sold Out",
                "Sunflowers",
                "id Software",
                "Maxis",
                "Pinnacle",
                "Xicat Interactive",
                "Devolver Digital",
                "Number None",
                "Strategy First",
                "Lexicon Entertainment",
                "GOA",
                "Avanquest",
                "Graphsim Entertainment",
                "Codemasters Online",
                "Stainless Games",
                "10TACLE Studios",
                "FuRyu Corporation",
                "Visco",
                "Crimson Cow",
                "Lighthouse Interactive",
                "CDV Software Entertainment",
                "Encore",
                "Blue Byte",
                "NewKidCo",
            ],
        },
        {
            "identifier": "Genre",
            "label": "Select Genre:",
            "type": "select",
            "options": [
                "Sports",
                "Racing",
                "Platform",
                "Misc",
                "Action",
                "Puzzle",
                "Shooter",
                "Fighting",
                "Simulation",
                "Role-Playing",
                "Adventure",
                "Strategy",
            ],
        },
        {
            "identifier": "Platform",
            "label": "Select Platform:",
            "type": "select",
            "options": [
                "Nintendo",
                "Nintendo DS",
                "Xbox",
                "PlayStation",
                "Other_plat",
                "PC",
                "Other Handhelds",
                "Other Consoles",
            ],
        },
    ],
)


# EOF
